#open calcium imaging scripts library - includes all scripts except functions included at the bottom here.
#devtools::install_github("SenguptaLab/MF.matR")
library(MF.matR)

#plotGCaMP_multi to analyze all traces/genotypes, includes background subtraction (backsub = TRUE)
#set cue, genotype, and neuron specific to conditions
wt<-plotGCaMP_multi(cue = pyrazine, 
                    genotype = wt,
                    neuron = AWA, 
                    show.plots = FALSE,
                    backsub = TRUE,
                    heatmap_limits = c(-.05,0,.3))
wt$data 
wt$plot

#pool data, unnest data
alldata <- rbind(genotype1$data, genotype2$data)
unnested <- unnest(alldata)

#get mean and SEM for all genotypes 
alldata.mean <- unnested %>%
  unnest() %>%
  group_by(time, genotype) %>%
  summarise(meanDelF = mean(delF),
            n = n(),
            sem.low = meanDelF - sd(delF) / n()^0.5, 
            sem.high = meanDelF + sd(delF) / n()^0.5)

#plot mean +/- SEM 
alldata.mean %>%
  ggplot(aes(x = time, y = meanDelF)) +
  geom_line(aes(colour = genotype), alpha = 1) + #mean line
  geom_ribbon(aes(ymin = sem.low, ymax = sem.high, fill = genotype), alpha = 0.2) +
  coord_cartesian(ylim = c(-.1, .40)) +
  geom_segment(aes(x = 30, xend = 40, y = .7, yend = .7), colour = "black", size = .5) +
  coord_cartesian(xlim = c(25, 45)) +
  theme_classic()

#plot overlaid calcium traces for adaptation or multiple pulse experiments
habit_baseline_pulses(genotype = "genotype1") #open raw .csv PlotCaMP_multi file
habit_baseline_pulses(genotype = "genotype2") #open raw .csv PlotCaMP_multi file

#Analyze exponential decay for each pulse: re-calculate/verify t 1/2 using PRISM
####for one pulse:
desens_decay_extract(genotype = "genotype1", n_pulses = 1)
desens_decay_extract(genotype = "genotype2", n_pulses = 1)
####for multiple pulses:
decay_baseline_correct(genotype = "genotype1") #open habit_baseline_pulses .csv file
decay_baseline_correct(genotype = "genotype2") #open habit_baseline_pulses .csv file

#Habituation analysis of peak response per pulse:
habituation(genotype = "genotype1") #open plotGCaMPmulti.csv file
habituation(genotype = "genotype2") #open plotGCaMPmulti.csv file

habituation_normalized(genotype = "genotype1") #open habituation.csv file
habituation_normalized(genotype = "genotype2") #open habituation.csv file

##to plot just the second pulse for ASH glycerol experiments
pulse2 <- alldata %>%
  unnest() %>%
  filter(time > 90, time < 181) 
pulse2 %>%
  ggplot(aes(x = time, y = delF, group = genotype)) +
  stat_summary(geom = "line", fun.y = mean, aes(colour = genotype)) +
  stat_summary(geom = "ribbon", fun.data = mean_se, alpha = 0.2, aes(fill = genotype))

baselines <- pulse2 %>%
  filter(time > 100, time < 119) %>%
  group_by(genotype) %>%
  summarize(meanDelf = mean(delF))

# join  pulse2 and baselines
corrected_pulse2 <- full_join(pulse2, baselines) %>%
  mutate(correct_delF = delF - meanDelf)

corrected_pulse2 %>%
  ggplot(aes(x = time, y = correct_delF, group = genotype)) +
  stat_summary(geom = "line", fun.y = mean, aes(colour = genotype)) +
  stat_summary(geom = "ribbon", fun.data = mean_se, alpha = 0.2, aes(fill = genotype)) +
  geom_segment(aes(x =120, xend = 150, y = 1, yend = 1), colour = "black", size = .75) + 
  theme_classic()

#####FUNCTIONS####

##### 1) a function to calculate peak delta F/ F changes for habituation analysis (called habituation)
##to analyze habituation across multiple pulses
##habituation analysis- type function like this: habituation(genotype = "WT")
##then select the ".csv" corresponding file per genotype (generated by plotGCaMPmulti)
habituation <- function(genotype, end = 30, ...) {
  #first get a directory path to use for saving:
  message("choose your habituation data file")  
  filename <- file.choose()
  
  data <- read_csv(filename)
  
  data <- data %>%
    mutate(pulse_num = ceiling(time/60),
           pulse_time = time - (pulse_num - 1)*60)
  
  peakPulses <- data %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    summarize(peak_delF = max_delta(delF, end = end)) # max of 20 frames after 'end' of the pre-pulse window, minus mean of 10 frames prior (max F-F0/F0 - mean baseline F-F0/F0)
  
  p <- peakPulses %>% ggplot(aes(x = pulse_num, y = peak_delF)) + geom_point()
  print(p)
  #write_csv(peakPulses, glue::glue(dirname(filename), "/", {genotype}, "_habituation.csv"))
  write_csv(peakPulses, file.path(dirname(filename), 
                                  glue::glue({genotype}, "_habituation.csv")))
  print(file.path(dirname(filename), glue::glue({genotype}, "_habituation.csv")))
}

##### 2) a function to calculate normalized peak delta F/F changes for habituation analysis (called habituation_normalized)

##to analyze habituation across multiple pulses, normalized to the largest response 
##type function like this: habituation_normalized(genotype = "WT")
##then select the "habituation.csv" corresponding file per genotype
habituation_normalized <- function(genotype){
  message("choose your habituation data file")
  filename <- file.choose()
  
  data <- read_csv(filename)
  
  data2 <- data %>%
    group_by(animal_num) %>%
    summarize(pulsepeak_delF = max(peak_delF))
  
  data3 <- dplyr::full_join(data, data2) %>% mutate(normalized_delF = peak_delF/pulsepeak_delF)
  
  write_csv(data3, file.path(dirname(filename), 
                             glue::glue({genotype}, "_normalizedhabituation.csv")))
  print(file.path(dirname(filename), glue::glue({genotype}, "_normalizedhabituation.csv")))
  
}

##### 3) a function to plot delta F / F for each pulse overlaid (called habit_pulses_plot)

#a function to plot delta F / F for each pulse overlaid 
habit_pulses_plot <- function(genotype, pulse_dur = 60, write_data = TRUE, n_pulses = 6) {
  
  library(tidyverse)
  library(magrittr)
  theme_set(theme_classic())
  filename <- file.choose()
  dataset <- read_csv(filename)
  # Choose your dataset (*.csv)
  
  dataset %<>%
    mutate(pulse_num = ceiling(time/pulse_dur),
           pulse_time = time - (pulse_num - 1)*pulse_dur)
  
  dataset <- dataset %>%
    ggplot(aes(x = pulse_time, y = delF)) +
    annotate("rect", xmin = 30, xmax = 40, ymin = -.05, ymax = 0.6,
             alpha = .05, colour = "grey") +
    stat_summary(geom = "ribbon", fun.data = "mean_se",
                 alpha = 0.1, aes(group = pulse_num, fill = pulse_num)) +
    stat_summary(aes(group = pulse_num, colour = pulse_num), geom = "line", fun.y = "mean") +
    coord_cartesian(xlim = c(25,45)) +
    viridis::scale_color_viridis() +
    viridis::scale_fill_viridis() +
    labs(x = "time (s)", y = paste0("Delta F / F0")) +
    guides(colour = guide_legend("Pulse number"),
           fill = guide_legend("Pulse number"))
  
  print(dataset)
  
}

##### 4) a function to plot delta F / F for each pulse normalized to each baseline prior to the pulse overlaid (called habit_baseline_pulses)

habit_baseline_pulses <- function(genotype, pulse_dur = 60, write_data = TRUE, n_pulses = 6) {
  
  library(tidyverse)
  library(magrittr)
  theme_set(theme_classic())
  filename <- file.choose()
  dataset <- read_csv(filename)
  # Choose your dataset (*.csv)
  
  dataset %<>%
    mutate(pulse_num = ceiling(time/pulse_dur),
           pulse_time = time - (pulse_num - 1)*pulse_dur)
  
  ###### baseline correct pre-pulse #####
  dataset <- dataset %>%
    filter(pulse_time > 25 & pulse_time < 29) %>% # get just pre-pulse values
    group_by(genotype, pulse_num, animal) %>% # group by pulse (and potentially other things to add here)
    summarise(baseline = mean(delF)) %>%
    full_join(., dataset) %>%
    mutate(corrected_delF = delF - baseline) %>%
    filter(pulse_num <= n_pulses)
  
  plot <- dataset %>%
    ggplot(aes(x = pulse_time, y = corrected_delF)) +
    annotate("rect", xmin = 30, xmax = 40, ymin = -.05, ymax = 0.6,
             alpha = .05, colour = "grey") +
    stat_summary(geom = "ribbon", fun.data = "mean_se",
                 alpha = 0.1, aes(group = pulse_num, fill = pulse_num)) +
    stat_summary(aes(group = pulse_num, colour = pulse_num), geom = "line", fun.y = "mean") +
    coord_cartesian(xlim = c(25,45)) +
    viridis::scale_color_viridis() +
    viridis::scale_fill_viridis() +
    labs(x = "time (s)", y = paste0("Delta F / F0")) +
    guides(colour = guide_legend("Pulse number"),
           fill = guide_legend("Pulse number"))
  
  print(plot)
  
  if(write_data) {
    write_csv(dataset, file.path(dirname(filename),
                                 glue::glue({genotype}, "_habit_baseline_pulses.csv")))
    message("Filtered results written to:")
    print(file.path(dirname(filename), glue::glue({genotype}, "_habit_baseline_pulses.csv")))
  }
  
}

##### 5) a function to analyze only the second pulse when imaging two pulses (i.e. 1M Glycerol experiments) - creates csv file (called corrected_secondpulse)

#how to analyze only the second pulse when imaging two pulses (i.e. 1M Glycerol experiments) - creates csv file
corrected_secondpulse <- function(genotype) {
  #first get a directory path to use for saving:
  message("choose your csv data file")  
  filename <- file.choose()
  
  data <- read_csv(filename)
  
  pulse2 <- data %>%   
    unnest() %>%   
    filter(time > 90, time < 181)    #filter for data between 90 - 181 (second pulse)
  
  baselines <- pulse2 %>%
    filter(time > 100, time < 119) %>%
    group_by(genotype) %>%
    summarize(meanDelf = mean(delF)) #assigning the mean of values 100 - 119 to "meanDelf"
  
  # join  pulse2 and baselines data
  corrected_pulse2 <- full_join(pulse2, baselines) %>%
    mutate(correct_delF = delF - meanDelf) #make a new column for del - meanDelf = this substracts the mean F for values 100 - 119 from ALL F-F0/F0 values
  
  write_csv(corrected_pulse2, file.path(dirname(filename), 
                                        glue::glue({genotype}, "_correctedpulse2.csv")))
  print(file.path(dirname(filename), glue::glue({genotype}, "_correctedpulse2.csv")))
}

##### 6) a function to extract values for each pulse and copy to csv file: max > 40 seconds for fit to exponential decay (called desens_decay_extract)

#script to extract values for each pulse and copy to csv file: max > 40 seconds for fit to exponential decay
#also determines t1/2 for each calcium trace
#open plotGCaMP_multi csv raw file
#on plots - dashed lines = fit
desens_decay_extract <- function(genotype, #mandatory genotype, should be text
                                 pulse_length = 60, # time of pulse in seconds 
                                 stim_length = 10, # time of stimulus in seconds
                                 pre_pulse = 30, # time before each pulse in seconds
                                 n_pulses = 5) {
  
  library(tidyverse)
  library(magrittr)
  # pulse_length <- 60
  # stim_length <- 10
  # n_pulses <- 5
  
  filename <- file.choose()
  data <- read_csv(filename)
  
  ###### read in data and divide by pulse length #####
  data <- data %>%
    mutate(pulse_num = ceiling(time/pulse_length),
           pulse_time = time - (pulse_num - 1)*pulse_length)
  
  ###### Get the time of the max delF after pulse initiation, but before #####
  ######      removal
  postPulse_data <- data %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    filter(pulse_time > (pre_pulse-2) & pulse_time < (pre_pulse + stim_length - 0.5)) %>%
    select(-signal, -MeanGCaMP, -MeanBackground, -fitted) %>% #get rid of some useless columns
    mutate(row_number = row_number()) # first add a row_number column to use as index
  
  peak_rows <-data %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    filter(pulse_time > (pre_pulse-2) & pulse_time < (pre_pulse + stim_length - 0.5)) %>%
    summarize(peak = which.max(delF)) # gives the index (row number) of max value
  
  ##### now filter each pulse to take only times > than peak #####
  decay_data <- full_join(postPulse_data, peak_rows) %>%
    filter(row_number >= peak) %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    mutate(new_row_number = row_number(),
           decay_time = new_row_number*0.25) 
  
  #### plot result for pulse
  plot1 <- decay_data %>%
    filter(pulse_num < (n_pulses + 1)) %>%
    ggplot(aes(x = decay_time, y = delF)) +
    geom_line(aes(group = animal, colour = animal_num)) + 
    facet_wrap(~pulse_num) +
    guides(color = guide_legend("Pulse number"))
  print(plot1)
  
  # in this model k = exp(lrc) and y(t) = c + y0*exp(-k*t)
  # so ln(delF0 / .5 * delF0) = k * t(1/2), so ln(2)/k = t(1/2)
  # final function is ln(2)/exp(lrc) = t(1/2)
  
  half_time_getter <- function(fit) {
    lrc <- fit %>% broom::tidy() %>%
      filter(term == "lrc") %>%
      select(estimate) %>%
      as.numeric()
    half_time <- log(2)/exp(lrc)
    return(half_time)
  }
  
  p.val_getter <- function(fit) {
    p.value <- fit %>% broom::tidy() %>%
      filter(term == "lrc") %>%
      select(p.value) %>%
      as.numeric()
    return(p.value)
  }
  
  #### fit nls to the data ####
  decay_data_fit <- decay_data %>%
    filter(pulse_num < n_pulses + 1) %>%
    group_by(animal, animal_num, pulse_num) %>%
    nest() %>%
    mutate(fit = map(data, ~try(nls(delF ~ SSasymp(decay_time, Asym, R0, lrc),
                                    data = .x))))
  
  #### Get half-time, p.value and predictions from fits ####
  decay_data_fit %<>%
    mutate(fit_result = 
             case_when(
               class(unlist(fit)) == "character" ~ "error",
               TRUE ~ "fit"))
  
  fit_results <- decay_data_fit %>% 
    select(animal, animal_num, pulse_num, fit_result)
  
  decay_data_fit %<>%
    filter(fit_result == "fit") %>%
    mutate(half_time = map(fit, half_time_getter) %>% unlist(),
           p.value = map(fit, p.val_getter) %>% unlist(),
           predictions = map(fit, function(x) {predict(x)}))
  
  plot <- decay_data_fit %>%
    unnest(cols = c(data, predictions)) %>%
    ggplot(aes(x = decay_time, y = delF)) +
    geom_line(aes(group = animal, colour = animal_num)) + 
    geom_line(aes(group = animal, 
                  colour = animal_num, y = predictions), 
              lty = 2) +
    facet_wrap(~pulse_num) +
    guides(color = guide_legend("Pulse number"))
  print(plot)
  
  fit_results <- full_join(decay_data_fit, fit_results) %>%
    select(animal, animal_num, pulse_num, fit_result, half_time, p.value)
  
  write_csv(decay_data, file.path(dirname(filename), glue::glue({genotype},"_decay_data.csv")))
  
  write_csv(fit_results, 
            file.path(dirname(filename),
                      glue::glue({genotype},
                                 "_desens_decay_extract.csv")))
  
  ggsave(plot, filename = file.path(dirname(filename),
                                    glue::glue({genotype},
                                               "_desens_decay_plots.png")),
         width = 11, height = 8.5, units = "in")
  
  message("results written to:")
  print(file.path(dirname(filename), 
                  glue::glue({genotype}, 
                             "_desens_decay_extract.csv")))
  
}

##### 7) a function to extract values for each pulse and copy to csv file: max > 40 seconds - for BASELINE CORRECTED fit to exponential decay (called decay_baseline_correct)

#script to extract values for each pulse and copy to csv file: max > 40 seconds - for BASELINE CORRECTED fit to exponential decay (supplied from habit_baseline_pulses function)
#also determines t1/2 for each calcium trace
#open habit_baseline_pulses .csv file
#on plots - dashed lines = fit
decay_baseline_correct <- function(genotype, #mandatory genotype, should be text
                                   pulse_length = 60, # time of pulse in seconds 
                                   stim_length = 10, # time of stimulus in seconds
                                   pre_pulse = 30, # time before each pulse in seconds
                                   n_pulses = 5) {
  
  library(tidyverse)
  library(magrittr)
  # pulse_length <- 60
  # stim_length <- 10
  # n_pulses <- 5
  
  filename <- file.choose()
  data <- read_csv(filename)
  
  ###### Get the time of the max delF after pulse initiation, but before #####
  ######      removal
  postPulse_data <- data %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    filter(pulse_time > (pre_pulse-2) & pulse_time < (pre_pulse + stim_length - 0.5)) %>%
    select(-signal, -MeanGCaMP, -MeanBackground, -fitted) %>% #get rid of some useless columns
    mutate(row_number = row_number()) # first add a row_number column to use as index
  
  peak_rows <-data %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    filter(pulse_time > (pre_pulse-2) & pulse_time < (pre_pulse + stim_length - 0.5)) %>%
    summarize(peak = which.max(delF)) # gives the index (row number) of max value
  
  ##### now filter each pulse to take only times > than peak #####
  decay_data <- full_join(postPulse_data, peak_rows) %>%
    filter(row_number >= peak) %>%
    group_by(genotype, animal, animal_num, pulse_num) %>%
    mutate(new_row_number = row_number(),
           decay_time = new_row_number*0.25) 
  
  #### plot result for pulse
  plot1 <- decay_data %>%
    filter(pulse_num < (n_pulses + 1)) %>%
    ggplot(aes(x = decay_time, y = delF)) +
    geom_line(aes(group = animal, colour = animal_num)) + 
    facet_wrap(~pulse_num) +
    guides(color = guide_legend("Pulse number"))
  print(plot1)
  
  # in this model k = exp(lrc) and y(t) = c + y0*exp(-k*t)
  # so ln(delF0 / .5 * delF0) = k * t(1/2), so ln(2)/k = t(1/2)
  # final function is ln(2)/exp(lrc) = t(1/2)
  
  half_time_getter <- function(fit) {
    lrc <- fit %>% broom::tidy() %>%
      filter(term == "lrc") %>%
      select(estimate) %>%
      as.numeric()
    half_time <- log(2)/exp(lrc)
    return(half_time)
  }
  
  p.val_getter <- function(fit) {
    p.value <- fit %>% broom::tidy() %>%
      filter(term == "lrc") %>%
      select(p.value) %>%
      as.numeric()
    return(p.value)
  }
  
  #### fit nls to the data ####
  decay_data_fit <- decay_data %>%
    filter(pulse_num < n_pulses + 1) %>%
    group_by(animal, animal_num, pulse_num) %>%
    nest() %>%
    mutate(fit = map(data, ~try(nls(corrected_delF ~ SSasymp(decay_time, Asym, R0, lrc),
                                    data = .x))))
  
  #### Get half-time, p.value and predictions from fits ####
  decay_data_fit %<>%
    mutate(fit_result = 
             case_when(
               class(unlist(fit)) == "character" ~ "error",
               TRUE ~ "fit"))
  
  fit_results <- decay_data_fit %>% 
    select(animal, animal_num, pulse_num, fit_result)
  
  decay_data_fit %<>%
    filter(fit_result == "fit") %>%
    mutate(half_time = map(fit, half_time_getter) %>% unlist(),
           p.value = map(fit, p.val_getter) %>% unlist(),
           predictions = map(fit, function(x) {predict(x)}))
  
  plot <- decay_data_fit %>%
    unnest(cols = c(data, predictions)) %>%
    ggplot(aes(x = decay_time, y = corrected_delF)) +
    geom_line(aes(group = animal, colour = animal_num)) + 
    geom_line(aes(group = animal, 
                  colour = animal_num, y = predictions), 
              lty = 2) +
    facet_wrap(~pulse_num) +
    guides(color = guide_legend("Pulse number"))
  print(plot)
  
  fit_results <- full_join(decay_data_fit, fit_results) %>%
    select(animal, animal_num, pulse_num, fit_result, half_time, p.value)
  
  write_csv(decay_data, file.path(dirname(filename), glue::glue({genotype},"_decay_baseline_correct.csv")))
  
  write_csv(fit_results, 
            file.path(dirname(filename),
                      glue::glue({genotype},
                                 "_decay_baseline_correct_fit_results.csv")))
  
  ggsave(plot, filename = file.path(dirname(filename),
                                    glue::glue({genotype},
                                               "_decay_baseline_correct_plots.png")),
         width = 11, height = 8.5, units = "in")
  
  message("results written to:")
  print(file.path(dirname(filename), 
                  glue::glue({genotype}, 
                             "_decay_baseline_correct.csv")))
  
}

